version: "3.8"
services:
   craiglist_db:
      image: postgres:${POSTGRES_VERSION}
      container_name: craiglist_db
      restart: always
      volumes:
        - db-data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "${POSTGRES_PORT}:5432"
       
   craiglist_adminer:
      image: adminer
      depends_on:
        - craiglist_db
      restart: always
      container_name: craiglist_adminer
      ports:
        - 8080:8080

   craiglist_web:
      build:
        context: .
        dockerfile: .docker/python/Dockerfile
      container_name: craiglist_web
      working_dir: /home/app/web
      command: python manage.py runserver 0.0.0.0:8000 && python manage.py migrate
      volumes:
        - .:/home/app/web/
      ports:
        - 8000:8000
      environment:
        DEBUG: ${DEBUG}
        SECRET_KEY: ${SECRET_KEY}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_NAME: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      depends_on:
        - craiglist_db

volumes:
  db-data: